"""Interface for notifier admin client."""

from typing import Any, Protocol


class INotifierClient(Protocol):
    async def get_config(self) -> dict[str, Any]: ...
    async def put_config(
        self, trigger_event: str, recipient_role: str, channel: str, body: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def unisender_templates(self, *, refresh: bool) -> dict[str, Any]: ...
    async def telegram_preview(self, body: dict[str, Any]) -> dict[str, Any]: ...
